name: Scrape Recipes

on: [push]

jobs:
  run-scraper:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: node index.js --fn
      - name: Upload data
        uses: actions/upload-artifact@v3
        with:
          name: scrape-data
          path: data_fn.json
